# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - workout-tracker-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release  # Define la configuración de build

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./WorkoutTrackerAPI/WorkoutTrackerAPI.sln

      - name: Build application
        run: dotnet build ./WorkoutTrackerAPI/WorkoutTrackerAPI.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: dotnet publish
        run: dotnet publish ./WorkoutTrackerAPI/WorkoutTrackerAPI.sln -c ${{ env.BUILD_CONFIGURATION }} -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7644162EFD034B18A4CFBB87C979CACC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_59A1E6216C4141E49C8B963876D6605C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B16D8BD56BF4429BBF24D20BD0F89810 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'workout-tracker-api'
          slot-name: 'Production'
          package: .